# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Zhang Yufan"
repo_name: "arxiv-papers-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: True

# file paths
json_readme_path: './docs/arxiv-papers-daily.json'
json_gitpage_path: './docs/arxiv-papers-daily-web.json'
json_wechat_path: './docs/arxiv-papers-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Depth Estimation":
        filters: ["Depth Estimation", "Stereo Matching", "Multi-View Stereo"]
    "Gesture Recognition":
        filters: ["Gesture Recognition", "Hand Tracking", "Gesture Classification"]
    "Eye Tracking":
        filters: ["Eye Tracking", "Gaze Estimation"]
    "VLM/LLM":
        filters: ["Large Language Model", "LLM", "Vision Language Model", "VLM", "Multi-modal Model", "Embodied AI"]
    "Diffusion":
        filters: ["Diffusion", "Diffusion Models", "Text to 3D", "Image to 3D"]
    "Neural Rendering":
        filters: ["Neural Rendering", "Gaussian Splatting", "3D GS", "NeRF", "Neural Radiance Fields", "SDF", "Signed Distance Funciton"]